---
- name: ADD APT GPGs
  apt_key:
    url: "{{ item }}"
    state: present
  become: true
  with_items: "{{ apt.gpg }}"
- name: ADD APT REPOSITORIES
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ apt.repositories }}"
- name: UPDATE AND UPGRADE APT PACKAGES
  become: true
  apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400
- name: INSTALL APT PACKAGES
  become: true
  apt:
    pkg: "{{ apt.packages }}"
    state: latest # noqa package-latest
    update_cache: true
